### ISSUE TITLE
mmpose library has been upgraded to 1.0.0, causing incompatibility

### ISSUE THREAD

**Issue by narugo1992** [hysts/anime-face-detector#16]
As the title...

Here is the error on Github Action: https://github.com/narugo1992/games_character_ranking/actions/runs/4632168314/jobs/8195918863#step:9:129

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/__main__.py", line [100](https://github.com/narugo1992/games_character_ranking/actions/runs/4632168314/jobs/8195918863#step:9:101), in <module>
    cli()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/click/core.py", line [105](https://github.com/narugo1992/games_character_ranking/actions/runs/4632168314/jobs/8195918863#step:9:106)5, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/__main__.py", line 56, in update
    create_ranking_project(game, output_dir, number, icon_size, mode, min_recent_count, f'{recent_days} days')
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/project.py", line 97, in create_ranking_project
    all_chars, images_dir, count, icon_size, mode, _existing_image_filenames)
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/project.py", line 36, in create_ranking_table
    logo_image = get_logo(ch, min_size=icon_size)
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/games.py", line 88, in get_logo
    from .image import find_heads
  File "/home/runner/work/games_character_ranking/games_character_ranking/ranking/image.py", line 7, in <module>
    from anime_face_detector import create_detector
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/anime_face_detector/__init__.py", line 5, in <module>
    from .detector import LandmarkDetector
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/anime_face_detector/detector.py", line 12, in <module>
    from mmpose.apis import inference_top_down_pose_model, init_pose_model
ImportError: cannot import name 'inference_top_down_pose_model' from 'mmpose.apis' (/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/mmpose/apis/__init__.py)
```

When I set `mmpose<1`, it's okay.

**Comment by ifenghao** [comment]
same here, refer to mmpose.apis document, "inference_top_down_pose_model" seems to be removed
https://mmpose.readthedocs.io/en/latest/api.html

**Comment by Obamium69** [comment]
Is there a workaround?

**Comment by SystemErrorWang** [comment]
same problem here, any update?
